config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tweets do
    collection do
      get :global
    end
  end

  resources :users, only: [:show] do
    member do
      get :following
      get :followers
    end
    collection do
      get :search
      get :search_user
      get :search_tweet
    end
  end

  post   '/like/:tweet_id' => 'likes#like',   as: 'like'
  delete '/like/:tweet_id' => 'likes#unlike', as: 'unlike'

  post   '/follow/:user_id' => 'users#follow', as: 'follow'
  delete '/follow/:user_id' => 'users#unfollow', as: 'unfollow'

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # ユーザーネームについて半角英数字と記号（ - _ ）のみ許可
  VALID_EMAIL_REGEX = /\A[\w_-]*[A-Za-z][\w_-]*\z/
  validates :username, format: { with: VALID_EMAIL_REGEX }

  has_many :tweets, dependent: :destroy

  # いいね機能のアソシエーション
  has_many :likes, dependent: :destroy
  has_many :like_tweets, through: :likes, source: :tweet

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  mount_uploader :icon, IconUploader
  mount_uploader :wallpaper, WallpaperUploader

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end


  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :username, :introduction, :icon, :wallpaper])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(tweet_id: @tweet.id)
    if like.save
    else
      redirect_to :back, alert: "いいね！に失敗しました"
    end
  end

  def unlike
    like = current_user.likes.find_by(tweet_id: @tweet.id)
    if like.destroy
    else
      redirect_to :back, alert: "いいね！削除に失敗しました"
    end
  end

  private

  def set_variables
    @tweet = Tweet.find(params[:tweet_id])
    @id_name = "#like-link-#{@tweet.id}"
    @id_heart = "#heart-#{@tweet.id}"
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :current_user_confirm, only: [:edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    ids = current_user.followings.ids
    ids << current_user.id
    @tweets = Tweet.where(user_id: ids).order(created_at: :DESC)
    @new_tweet = Tweet.new
    @global = false
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @liking_users = @tweet.liking_users.order(created_at: :DESC)
    @new_tweet = Tweet.new
  end

  # GET /tweets/new
  def new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'ツイートを投稿しました' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'ツイートを編集しました！' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def global
    @global = true
    @tweets = Tweet.order(created_at: :DESC)
    @new_tweet = Tweet.new
    render :index
  end

  private

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:content, :image)
    end

    def current_user_confirm
      if current_user.id != @tweet.user.id
        redirect_to :back, alert: "あなたはこのツイートの投稿者ではありません"
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :new_tweet

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.order(created_at: :desc)
    @like_tweets = @user.like_tweets.order(created_at: :desc)
    @liked = 0
    @tweets.each do |tweet|
      @liked += tweet.likes.count
    end
  end

  def follow
    @user = User.find(params[:user_id])
    current_user.follow!(@user)
    redirect_to :back, notice: "フォローしました"
  end

  def unfollow
    @user = User.find(params[:user_id])
    current_user.unfollow!(@user)
    redirect_to :back, notice: "アンフォローしました"
  end

  def search
    @global = true
    @search = params[:search]
    tweet_ids = Like.group(:tweet_id).order('count_tweet_id DESC').limit(10).count(:tweet_id).keys
    @like_tweets = tweet_ids.map { |id| Tweet.find(id) }
  end

  def search_user
    @users_except_me = User.where.not(id: current_user.id)
    @users = @users_except_me.where('nickname LIKE(?)', "%#{params[:user]}%")
    render json: @users
  end

  def search_tweet
    @tweets = Tweet.where('content LIKE(?)', "%#{params[:tweet]}%").order(created_at: :desc)
    respond_to do |format|
      format.json
    end
  end

  private

  def new_tweet
    @new_tweet = Tweet.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
%header
  .header-wrapper
    .container
      .fa.fa-twitter
      -if current_user
        %ul.nav-left
          = link_to global_tweets_path do
            %li.head-btn.btn-default.glyphicon.glyphicon-globe
              グローバル
          = link_to tweets_path do
            %li.head-btn.btn-default.glyphicon.glyphicon-home
              ホーム
          / %li.head-btn.btn-default.glyphicon.glyphicon-stats
          /   モーメント
          / %li.head-btn.btn-default.glyphicon.glyphicon-bell
          /   通知
        .nav-right
          = form_tag("/users/search", method: :get) do
            %input.right-btn-input{ name: "search", placeholder: "キーワード検索"}
            %input.input-submit-btn{ id: "submit-search",type: "submit"}
              %label.glyphicon.glyphicon-search{ for: "submit-search"}
          %ul.right-btn
            = link_to user_path(current_user) do
              %li.glyphicon.glyphicon-user.btn
            %li.btn.btn-default.glyphicon.glyphicon-edit

-if @new_tweet
  = render 'tweets/tweet_modal', tweet: @new_tweet

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TECH::TWEET
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = render 'layouts/header'

  %body
    .body-wrapper
      - flash.each do |key, value|
        = content_tag(:div, value, class: "flash flash__#{key}")
      = yield

app/views/likes/_like_links.html.haml
%div.like-link{id: "like-link-#{tweet.id}"}
  - if current_user.likes.find_by(tweet_id: tweet.id)
    = link_to unlike_path(tweet.id), method: :delete, remote: true do
      .btn.btn-default.glyphicon.glyphicon-heart{id: "heart-#{tweet.id}"}
        = tweet.likes.count.to_s
  - else
    = link_to like_path(tweet.id), method: :post, remote: true do
      .btn.btn-default.glyphicon.glyphicon-heart-empty{id: "heart-#{tweet.id}"}
        = tweet.likes.count.to_s

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", tweet: @tweet  )) %>');
$("<%= @id_heart %>").removeClass('glyphicon-heart-empty');
$("<%= @id_heart %>").addClass('glyphicon-heart');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", tweet: @tweet  )) %>');
$("<%= @id_heart %>").addClass('glyphicon-heart-empty');
$("<%= @id_heart %>").removeClass('glyphicon-heart');

app/views/tweets/_left-content.html.haml
.left-content

  =link_to user_path(current_user) do
    .left-profile
      - if current_user.wallpaper.present?
        = image_tag(current_user.wallpaper.url, class: "left-cover")
      - else
        .left-cover

      .left-body
        .left-photo
          - if current_user.icon.present?
            = image_tag(current_user.icon.thumb.url, class: "left-photo-icon")
          - else
            .glyphicon.glyphicon-camera

        .left-user
          %h4.left-user-nickname
            = current_user.nickname
          %h5.left-user-username
            = "@" + current_user.username
        .left-tweet
          %ul
            %li
              %p ツイート
              %p.left-number #{current_user.tweets.count.to_s}
            %li
              %p フォロー
              %p.left-number #{current_user.followings.count}
            %li
              %p フォロワー
              %p.left-number #{current_user.followers.count}

  .left-weather
    #test
    #city-name
    #weather

app/views/tweets/_tweet_modal.html.haml
#apply-modal.apply-modal-wrapper
  .modal
    .close-modal
      .glyphicon.glyphicon-remove
    #apply-form
      %h3 ツイートする
      = form_for(tweet) do |f|
        - if tweet.errors.any?
          #error_explanation
            %h2
              = pluralize(tweet.errors.count, "error")
              prohibited this tweet from being saved:
            %ul
              - tweet.errors.full_messages.each do |message|
                %li= message
        .actions-tweet
          = f.text_area :content, placeholder: "いまどうしてる？", class: "field tweet-field"
          = f.file_field :image, class: "tweet-image"
          %br
          = f.submit "Tweet", class: "btn btn-default tweet-btn"

app/views/tweets/_tweet_profile.html.haml
- if @global == true
  .tweet-follow
    = render 'users/follow', user: tweet.user

= link_to user_path(tweet.user) do
  - if tweet.user.icon.present?
    = image_tag(tweet.user.icon.thumb.url, class: "tweet-icon")
  %object.tweets-nickname
    %h4
      = "#{tweet.user.nickname}"
  %object.tweets-username
    %h5
      = "@" + "#{tweet.user.username}"

app/views/tweets/_tweets.html.haml
.tweet-wrapper

  = render 'tweets/tweet_profile', tweet: tweet

  %p.tweets-content
    = tweet.content

  .tweets-image
    - if tweet.image.present?
      = image_tag(tweet.image.url, class: "tweet-image-border")
  %h5.tweets-time
    = tweet.created_at.strftime("%Y/%m/%d %H時%M分")

  = render 'likes/like_links', tweet: tweet

  = link_to :back do
    .btn.btn-default.glyphicon.glyphicon-retweet

  .btn-group
    = link_to '詳細', tweet, class: "btn btn-default"
    - if tweet.user.id == current_user.id
      = link_to '削除', tweet, method: :delete, class: "btn btn-default", data: { confirm: 'このツイートを本当に削除しますか?' }

app/views/tweets/index.html.haml
= render 'left-content'

.tweets-wrapper
  = render partial: 'tweets', collection: @tweets, as: :tweet

app/views/tweets/show.html.haml
= render 'tweets', tweet: @tweet

%br
  %ul.nav.nav-tabs
    %li.nav-item
      %a.nav-link{ href: "#reply-index", "data-toggle": "tab"}
        リプライ
    %li.nav-item.active
      %a.nav-link{ href: "#like-index", "data-toggle": "tab"}
        いいね
        #{@liking_users.count.to_s}
    %li.nav-item
      %a.nav-link{ href: "#retweet-index", "data-toggle": "tab"}
        リツイート

  .tab-content
    #reply-index.tab-pane
      実装予定
    #like-index.tab-pane.active
      - @liking_users.each do |user|
        .tweets-wrapper
          = render 'users/user_profile', user: user
    #retweet-index.tab-pane
      実装予定

app/views/users/_follow.html.haml
- if current_user.id != user.id
  - if current_user.following?(user)
    = link_to "フォロー中", unfollow_path(user), method: :delete, class: "btn btn-default unfollow-btn"
  - else
    = link_to "フォローする", follow_path(user), method: :post, class: "btn btn-default follow-btn"

app/views/users/_user_profile.html.haml
.tweet-wrapper
  .tweet-follow
    = render 'users/follow', user: user

  = link_to user_path(user) do
    - if user.icon.present?
      = image_tag(user.icon.thumb.url, class: "tweet-icon")
    %object.tweets-nickname
      %h4
        = "#{user.nickname}"
    %object.tweets-username
      %h5
        = "@" + "#{user.username}"
    .clear

app/views/users/search.html.haml
= render 'tweets/left-content'

%ul.nav.nav-tabs.search-tabs-head
  %li.nav-item
    %a.nav-link{ href: "#like-index", "data-toggle": "tab"}
      人気のツイート
  %li.nav-item.active
    %a.nav-link{ href: "#user-index", "data-toggle": "tab"}
      ユーザー検索
  %li.nav-item
    %a.nav-link{ href: "#tweet-index", "data-toggle": "tab"}
      ツイート検索

.tab-content.search-tabs-content
  #like-index.tab-pane
    .tweets-wrapper
      = render partial: 'tweets/tweets', collection: @like_tweets, as: :tweet

  #user-index.tab-pane.active
    .search-box
      %input#user-search{ class: "search-box-input",value: @search, placeholder: "検索するユーザー名を入力してください", autocomplete: "off" }
        .tweets-wrapper
          #user-search-result

  #tweet-index.tab-pane
    .search-box
      %input#tweet-search{ class: "search-box-input", value: @search, placeholder: "検索するキーワードを入力してください", autocomplete: "off" }
        .tweets-wrapper
          #tweet-search-result

app/views/users/search.js.erb
// function buildSearchHTML(user) {
//   var insertImage = "";
//   if (user.icon.thumb.url) {
//     insertImage = '<img src="' + user.icon.thumb.url +'" class="tweet-icon">';
//   }
//   var html =
//   '<a href="/users/' + user.id + '">' +
//     '<div class="tweet-wrapper">' +
//       '<div class="tweet-follow">' + '</div>' +
//       insertImage +
//       '<div class="tweets-nickname">' + '<h4>' + user.nickname + '</h4>' + '</div>' +
//       '<div class="tweets-username">' + '<h5>@' + user.username + '</h5>' + '</div>' +
//       '<div class="clear">' + '</div>' +
//     '</div>'
//   '</a>';
//   return html;
// }

// console.log("hey");

// var insertHTML = "";
// data.forEach(function(user) {
//   insertHTML += buildSearchHTML(user);
// });
// $('#user-search-result').html(insertHTML);

app/views/users/show.html.haml
.wallpaper
  - if @user.wallpaper.present?
    = image_tag(@user.wallpaper.url, class: "mypage-wallpaper")
  - else
    .mypage-wallpaper

- if @user.icon.present?
  = image_tag(@user.icon.url, class: "mypage-icon")
- else
  .mypage-icon アイコンを設定してください

.mypage
  %h2= @user.nickname
  %h3= "@" + @user.username
  %h5= @user.introduction

  - if @user.id == current_user.id
    = link_to '設定', edit_user_registration_path, class: "btn btn-default"
    = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-default"

  = render 'users/follow', user: @user
  %br
  %br

  = "いいねされた総数：" + @liked.to_s
  %br
  %br

  %ul.nav.nav-tabs
    %li.nav-item.active
      %a.nav-link{ href: "#tweet-index", "data-toggle": "tab"}
        ツイート
        #{@tweets.count.to_s}
    %li.nav-item
      %a.nav-link{ href: "#like-index", "data-toggle": "tab"}
        いいね
        #{@user.likes.count.to_s}
    %li.nav-item
      %a.nav-link{ href: "#follow-index", "data-toggle": "tab"}
        フォロー
        #{@user.followings.count.to_s}
    %li.nav-item
      %a.nav-link{ href: "#follower-index", "data-toggle": "tab"}
        フォロワー
        #{@user.followers.count.to_s}

  .tab-content.tab-content-mypage
    #tweet-index.tab-pane.active
      .tweets-wrapper
        = render partial: 'tweets/tweets', collection: @tweets, as: :tweet
    #like-index.tab-pane
      .tweets-wrapper
        = render partial: 'tweets/tweets', collection: @like_tweets, as: :tweet
    #follow-index.tab-pane
      - @user.followings.each do |user|
        .tweets-wrapper
          = render 'user_profile', user: user
    #follower-index.tab-pane
      - @user.followers.each do |user|
        .tweets-wrapper
          = render 'user_profile', user: user